In [ ]:
# step 1: Data loading and preprocessing
# dataset: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
import pandas as pd
dataset = pd.read_csv('IMDB Dataset.csv')

In [3]:
dataset.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [4]:
dataset = dataset.iloc[:20, 0].values

In [5]:
dataset.shape

(20,)

In [6]:
# step 2: One-Hot Encoding
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
voc_size = 10000
encoded_dataset = [one_hot(review, voc_size) for review in dataset]

In [8]:
# Step 3: Padding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length = 500
embedded_dataset = pad_sequences(encoded_dataset, padding='pre', maxlen=sent_length)
print(embedded_dataset)

[[   0    0    0 ... 5614 9377 8804]
 [   0    0    0 ... 8877 4941  735]
 [   0    0    0 ... 9076 1427 6554]
 ...
 [   0    0    0 ... 5321 5614 4752]
 [   0    0    0 ... 2607 8210 2778]
 [   0    0    0 ... 1427 8695 4414]]


In [10]:
# Step 4: Embedding
dim = 10000
model = Sequential()
model.add(Embedding(voc_size, 10000, input_length=sent_length))
model.compile('adam', 'mse')
model.build(input_shape=(None, sent_length)) # Explicitly build the model

c:\Users\Adarsh Kumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 500, 10000)     │   100,000,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000,000 (381.47 MB)

 Trainable params: 100,000,000 (381.47 MB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(np.expand_dims(embedded_dataset[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step


array([[[-0.00888906, -0.00237666, -0.01169237, ...,  0.04370696,
         -0.03999858, -0.0013508 ],
        [-0.00888906, -0.00237666, -0.01169237, ...,  0.04370696,
         -0.03999858, -0.0013508 ],
        [-0.00888906, -0.00237666, -0.01169237, ...,  0.04370696,
         -0.03999858, -0.0013508 ],
        ...,
        [-0.01570071,  0.04861263, -0.01660886, ..., -0.032477  ,
          0.01095609, -0.04034947],
        [ 0.0158619 , -0.03613809, -0.00362138, ...,  0.03936389,
          0.04835132, -0.01574396],
        [-0.00535849, -0.03701639,  0.00670928, ...,  0.00674977,
          0.02866349,  0.03053318]]], shape=(1, 500, 10000), dtype=float32)

In [14]:
model.predict(embedded_dataset)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 450ms/step


array([[[-0.00888906, -0.00237666, -0.01169237, ...,  0.04370696,
         -0.03999858, -0.0013508 ],
        [-0.00888906, -0.00237666, -0.01169237, ...,  0.04370696,
         -0.03999858, -0.0013508 ],
        [-0.00888906, -0.00237666, -0.01169237, ...,  0.04370696,
         -0.03999858, -0.0013508 ],
        ...,
        [-0.01570071,  0.04861263, -0.01660886, ..., -0.032477  ,
          0.01095609, -0.04034947],
        [ 0.0158619 , -0.03613809, -0.00362138, ...,  0.03936389,
          0.04835132, -0.01574396],
        [-0.00535849, -0.03701639,  0.00670928, ...,  0.00674977,
          0.02866349,  0.03053318]],

       [[-0.00888906, -0.00237666, -0.01169237, ...,  0.04370696,
         -0.03999858, -0.0013508 ],
        [-0.00888906, -0.00237666, -0.01169237, ...,  0.04370696,
         -0.03999858, -0.0013508 ],
        [-0.00888906, -0.00237666, -0.01169237, ...,  0.04370696,
         -0.03999858, -0.0013508 ],
        ...,
        [ 0.02290476, -0.03489972, -0.02932483, ...,  